### ISSUE TITLE
Do I need to import anything to use this?

### ISSUE THREAD

**Issue by hayk94** [mizzao/meteor-user-status#108]
Guys, excuse me for a noob question. But I am very new to the meteor stuff. So I installed this package but get errors of undefined variables like 

> W20160815-14:26:01.202(4)? (STDERR) ReferenceError: UserStatus is not defined
> W20160815-14:26:01.202(4)? (STDERR)     at server/main.js:5:3

I guess I need to import the package in my js files as well. What should I include? Or is it some other problem?

**Comment by lmachens** [comment]
You have to install the package first:
`meteor add mizzao:user-status`

And it is a good pratice to import the module:
`import { UserStatus } from 'meteor/mizzao:user-status';`
