### ISSUE TITLE
Changing the 'status' default property name

### ISSUE THREAD

**Issue by Timothy-Yoseph** [mizzao/meteor-user-status#117]
can i change the default property name??
coz it replaced when I made a user seeder.. 
thanks a lot

**Comment by merlinpatt** [comment]
At the moment, it is not possible to change the default property name. What does your user seeder look like?

**Comment by mizzao** [comment]
I'd suggest just making your user seeder use a different field.

**Comment by Timothy-Yoseph** [comment]
that's the problem.. my senior doesn't allow me to refactor the field. his reason is, too many uses in the files
but, I'll try to convinve him
thanks a lot guys
