### ISSUE TITLE
Online field removed after some time

### ISSUE THREAD

**Issue by bitomule** [mizzao/meteor-user-status#43]
I'm having an issue in my app, after some time the online field in the user is removed, even if user is still online.

Maybe during that time connection was lost and recovered at some point, if I reload the page online status is back.

Thanks :)

**Comment by mizzao** [comment]
Meteor 1.0.3.1 included [the following in the changelog](https://github.com/meteor/meteor/blob/devel/History.md#v1031-2015-jan-20):

> Fix inaccurate session statistics and possible multiple invocation of Connection.onClose callbacks.

That may have fixed this issue. If it persists and you can reproduce it, feel free to continue the discussion here.
