### ISSUE TITLE
Get IP of current user?

### ISSUE THREAD

**Issue by dalgard** [mizzao/meteor-user-status#50]
Can I use this package to get the IP or connection id of the user who is currently doing some action on the server, such as inserting a document in a collection?

This would be in order to have some superficial tracking of not logged in users. Thanks.

**Comment by mizzao** [comment]
You can already do that with `this.connection.clientAddress` in any method of call, whether you are using this package or not.

**Comment by dalgard** [comment]
Yes – thanks. The problem is that this.connection is undefined in the context where I need it:

```javascript
MyCollection.before.insert(function (user_id, doc) {
  doc.authorIP = this.connection.clientAddress;
});
```

**Comment by riaan53** [comment]
You can just call a meteor method and set a session var on response with the IP and/or connectionId and then you can use it anywhere on the client.

```
Meteor.methods({
    getConnectionInfo: function () {
        if (!!this.connection) {
            return [this.connection.id, this.connection.clientAddress];
        }
    }
})
```

**Comment by mizzao** [comment]
@dalgard I suggest you read up on how `this` works in Javascript. It looks like you are trying to use the `this` variable from a method call inside a collection hook, which has a completely different API. You will need to pass that value over somehow, such as by using a Meteor environment variable.

In your case such a variable already exists in the form of `DDP._CurrentInvocation`, so you can do something like `DDP._CurrentInvocation.get().connection.clientAddress` anywhere on the server while a method is being processed. However, in other cases you will have to set such an environment variable yourself.

**Comment by dalgard** [comment]
@riaan53 Thanks for the tip; need the value server-side, though.

@mizzao Really appreciate the info you're bringing to the table here! It's not that I don't understand javascript – I'm aware that those functions have a different context, but I thought I might leverage your library to get to the value. Your answer has helped me out beautifully, though (except for the small detail of using a "private" property, of course ;)).
