### ISSUE TITLE
UserStatus is not defined in test environment

### ISSUE THREAD

**Issue by abditus113** [mizzao/meteor-user-status#51]
I'm having strange issue with UserStatus in test environment. Running ```meteor test-packages``` fails with ```ReferenceError``` saying that UserStatus is not defined although package is properly included. 
Moreover such error appears: ```The package mizzao:user-status at 0.2.0 is incompatible with Meteor 0.9.0 or later.``` I've checked meteor directory and version 0.2.0 of user-status package indeed exists there. It gets installed while running ```meteor test-packages``` command. Explicitly pointing to use version 0.6.3 of user-status in on_test section of package.js solves the problem but that should not be necessary.
Here is the replication of the issue: https://github.com/abditus113/user-status-bug. Simply clone and run ```meteor test-packages```
Any idea why that might be happening?

**Comment by mizzao** [comment]
0.2.0 is a really old version and cannot be installed with recent versions of Meteor. `UserStatus` is not a global variable available in that version, so it's no surprise that it isn't defined.

Your `onUse` section should say `api.use("mizzao:user-status@VERSION");` while it is fine for the `onTest` section to omit the version.

**Comment by abditus113** [comment]
As I mentioned before the problem appears in test environment. Not specifying a version of user-status in ```onTest``` section leads to an error while executing ```meteor test-packages```. Running this command results in installing old 0.2.0 version of your package.
In ```onUse``` section I don't specify any version of the package and there is no problem with that.

**Comment by mizzao** [comment]
Specify a version in `onUse`, otherwise the test environment (which is separate from your app) will have no idea which version to use. The installation of 0.2.0 is probably a bug (with Meteor's package dependency resolver).

When you install the package in your app, it specifies a version which is why you don't see a problem outside the test environment.

**Comment by mizzao** [comment]
Seems like you resolved this - but feel free to leave a comment if there are still any issues.
