### ISSUE TITLE
_timesync issue

### ISSUE THREAD

**Issue by pihentagy** [mizzao/meteor-user-status#54]
Hi, maybe the same as https://github.com/mizzao/meteor-timesync/issues/17 I get very similar error when using user-status.

**Comment by mizzao** [comment]
Let's just discuss in that thread then.

Although it's an "error", things still work. Are you using Firefox?

**Comment by pihentagy** [comment]
Yes, that was Firefox, and yes, things seemed to work. I though you had a fix in that project, which could also be applied here.

**Comment by mizzao** [comment]
user-status has timesync as a dependency. Fixing it there would fix it here as well.

If anyone using Firefox wants to try and fix the headers to make this warning go away, then by all means ;-)
