### ISSUE TITLE
Fetching userId

### ISSUE THREAD

**Issue by sangyoo91** [mizzao/meteor-user-status#56]
```
Meteor.publish("userStatus", function() {
  return Meteor.users.find({ "status.online": true }, 
  	{ 
  		fields: { status:1, userId: Posts.find(id).userId } 
  	});
});
```

I'm trying to publish only the OP's status by grabbing the userId field from the posts attributes.

My intentions are so that it loads faster.

Apparently, I apparently am doing something wrong. 

Help please!

**Comment by jhuenges** [comment]
```javascript
Meteor.publish("userStatus", function() {
  return Meteor.users.find({ "status.online": true, userId: Posts.find(id).userId }, // You have to define here for what you are looking
    { 
        fields: { status:1 } // This only specifies what is published. 
    });
});
```
Hope this helps :)
[More information](http://docs.meteor.com/#/full/meteor_publish)

**Comment by mizzao** [comment]
So where is `id` even coming from in this publication? It seems you need to pass `id` in the subscription, and do something like

```js
Meteor.publish("postUserStatus", function(postId) {
  return Meteor.users.find({ "status.online": true, userId: Posts.findOne(postId).userId },
    { 
        fields: { status:1 } // This only specifies what is published. 
    });
});
```

Better yet, just publish a user status based on userId and not postId.

**Comment by sangyoo91** [comment]
@jhuenges @mizzao Thank you guys! I found a way to make it work. It happens I had the wrong understanding about pub/sub. I think I can write a better pub related to my original question thanks to you guys :) Always appreciate the great work mizzo :+1:
