### ISSUE TITLE
How to set the user login only one at the same time?

### ISSUE THREAD

**Issue by thearabbit** [mizzao/meteor-user-status#62]
I use `ian:accounts-ui-bootstrap-3`.
I want to set the user can login only one at the same time.
For example, I have "theara" user account to login app. When I login on PC1 (online), so I can't use the same user to login on PC2 (local network).
How to check user online or solve?

**Comment by mizzao** [comment]
Someone tried something here, it might help you:

> http://stackoverflow.com/q/24158790/586086

**Comment by yuomtheara** [comment]
Thanks for your reply, but I don't understand.
