### ISSUE TITLE
Is there a way to use different model?

### ISSUE THREAD

**Issue by caio-ribeiro-pereira** [mizzao/meteor-user-status#66]
I'd like to use a different model than common Meteor.user, and the quetion is: 
Is there a way to setup a different model for UserStatus?

**Comment by mizzao** [comment]
No, but the code is open source and you're free to fork and modify as you wish!

**Comment by caio-ribeiro-pereira** [comment]
Ok, I will study how to extend this kind of feature soon, thanks!

**Comment by caio-ribeiro-pereira** [comment]
Ok, I will study how to extend this kind of feature soon, thanks!
