### ISSUE TITLE
cannot install meteor-user-status

### ISSUE THREAD

**Issue by wakingdreamer** [mizzao/meteor-user-status#67]
when i run  meteor add mizzao:user-status to install it ,i got the errors like this:   

 /home/fitark/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150617-14:32:22.151(8)? (STDERR)                                             throw(ex);
W20150617-14:32:22.151(8)? (STDERR)                                                   ^
W20150617-14:32:22.152(8)? (STDERR) Error: status.idle is not allowed by the schema
W20150617-14:32:22.152(8)? (STDERR)   at getErrorObject (/home/fitark/projects/OasisPD1/OasisPD/.meteor/local/build/programs/server/packages/aldeed_collection2.js:393:15)
W20150617-14:32:22.153(8)? (STDERR)   at [object Object].doValidate (/home/fitark/projects/OasisPD1/OasisPD/.meteor/local/build/programs/server/packages/aldeed_collection2.js:376:13)
W20150617-14:32:22.153(8)? (STDERR)   at [object Object].Mongo.Collection.(anonymous function) [as update] (/home/fitark/projects/OasisPD1/OasisPD/.meteor/local/build/programs/server/packages/aldeed_collection2.js:178:31)
W20150617-14:32:22.153(8)? (STDERR)   at onStartup (/home/fitark/projects/OasisPD1/OasisPD/.meteor/local/build/programs/server/packages/mizzao_user-status.js:157:23)
W20150617-14:32:22.154(8)? (STDERR)   at /home/fitark/projects/OasisPD1/OasisPD/.meteor/local/build/programs/server/boot.js:229:5

**Comment by mizzao** [comment]
Interesting, you had a schema on `Meteor.users`. Not sure how we'd handle this properly in the future, but good to know.

**Comment by aramk** [comment]
This occurs with [Telescope](https://github.com/TelescopeJS/Telescope). I fixed it with this:
```
# Additional fields for mizzao:user-status.
userSchema = new SimpleSchema
  status:
    type: Object
    blackbox: true

Users.attachSchema(userSchema)
```

**Comment by lpatmo** [comment]
@aramk Which file did you put your fix in? I put it inside a `custom` package's `custom_fields.js`, and got this error: ```ReferenceError: userSchema is not defined```. I notice that in the telescope-users package it's in a `users.js` file.

**Comment by aramk** [comment]
@lpatmo I don't think you should be getting a `userSchema` not defined issue - the code snippet I had above was defining that variable in coffeescript and then using it below, so it should work in the `custom_fields.js` of the custom package. I had mine in a custom package file available on both the client and server.

**Comment by lpatmo** [comment]
Ah, turns out I had written `users.Schema = new SimpleSchema` instead of `userSchema = new SimpleSchema.` My bad earlier.

However, the integration with Telescope seems to be causing with registering new users now (see screenshot) -- and unlike on a clean instance, the active users count stays at 0 for logged-out users.

![screen shot 2016-01-03 at 7 17 42 pm](https://cloud.githubusercontent.com/assets/4512699/12082924/ddfafe68-b24e-11e5-8b0e-266f74c8a74e.jpg)

**Comment by aramk** [comment]
That's the original issue I had which the additional field is meant to fix. Basically `meteor-user-status` is attempting to store a "status" field in the user doc, but this is forbidden by Telescope without adding that as a field. Make sure that the code you've added is available on both the client and server in the package.js file.

**Comment by lpatmo** [comment]
@aramk Interesting -- thanks for clarifying. I added:

```
userSchema = new SimpleSchema({ 
  status: {
    type: Object,
    blackbox: true
  }
});
Users.attachSchema(userSchema);
```

to my custom/lib/custom_fields.js, and double-checked that custom-fields.js was included here:

```
  api.addFiles([
    'lib/custom_fields.js',
    'lib/template_modules.js',
    'lib/callbacks.js'
  ], ['client', 'server']);
```

Error in console:
```
I20160103-21:04:55.540(-8)? Exception while invoking method 'ATCreateUserServer' { stack: 'Error: status is required\n    at getErrorObject (packages/aldeed_collection2/packages/aldeed_collection2.js:425:1)\n    at [object Object].doValidate (packages/aldeed_collection2/packages/aldeed_collection2.js:408:1)\n    at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2/packages/aldeed_collection2.js:177:1)\n    at AccountsServer.Ap.insertUserDoc (accounts_server.js:1248:25)\n    at createUser (password_server.js:980:25)\n    at AccountsServer.Accounts.createUser (password_server.js:1049:10)\n    at [object Object].Meteor.methods.ATCreateUserServer (packages/useraccounts_core/lib/server_methods.js:103:1)\n    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:164:1)\n    at maybeAuditArgumentChecks (livedata_server.js:1698:12)\n    at livedata_server.js:708:19',
I20160103-21:04:55.540(-8)?   source: 'method' }
I20160103-21:04:55.540(-8)? Sanitized and reported to the client as: status is required [400]
I20160103-21:04:55.540(-8)?
```
(with the same error as screenshot above when I try registering a new user.)

Perhaps I'm missing something. :/

**Comment by aramk** [comment]
It could be a race condition when setting up the schemas? You could try
wrapping the definition in a Meteor.startup()? Also use a var userSchema to
avoid the variable leaking out of scope.

**Comment by MichaelJCole** [comment]
FWIW, I've been using this:

```
// Status module information  https://github.com/mizzao/meteor-user-status#basic-usage---online-state
  // Public and sent to any client

  'status':                  { type: Object, optional: true },
  'status.lastLogin.date':   { type: Date, optional: true },
  'status.lastLogin.ipAddr': { type: String, optional: true },
  'status.userAgent':        { type: String, optional: true },
  'status.idle':             { type: Boolean, optional: true },
  'status.lastActivity':     { type: Date, optional: true },
  'status.online': {
    type: Boolean,
    index: true,
    optional: true,
  },
```
