### ISSUE TITLE
Can I access user's Session in UserStatus.events?

### ISSUE THREAD

**Issue by evolross** [mizzao/meteor-user-status#75]
I want to use this package to clear a bunch of `Meteor.setIntervals` that the user may have started when they log out or disconnect.  The `setIntervals` need to keep running as they navigate through the app - which they do if you call a Meteor method in your `setInterval`. I store the `setInterval` handles in the user's `Session`.

My knee-jerk reaction would be to listen for `UserStatus.events.on("connectionLogout",...` and then check for any user started `Meteor.setIntervals` by going through their Session for known Session variable names.  Is this possible in the space that `UserStatus.events.on("connectionLogout",...` runs in?  There doesn't seem to be a way to do this on the client - if they close the browser nothing runs.

I'm currently playing with `this._session.socket.on("close", Meteor.bindEnvironment(function() {...` in my `Meteor.publish` calls, but that doesn't work well if they have multiple browser windows open to the app - haven't figured out how to test for that on my own. So if they have multiple windows open and close one - the code runs no matter what.

One more question, will `UserStatus.events.on("connectionLogout",...` fire if they close **one** browser window but still have another one open to the app?

**Comment by mizzao** [comment]
I'm not sure that I'd use `user-status` for this. I would actually just keep all timers on the server - for example, this might give you some ideas: https://github.com/HarvardEconCS/turkserver-meteor/blob/master/lib/timers_server.jsx

If a user is closing their tab, there's no way you would be able to get anything on the client side `Session` before the server has already lost the connection and it's too late.

`UserStatus.events.on("connectionLogout",...` fires per tab.

`Meteor.users.find({"status.online": true}).observe(...` fires only when the first tab joins or the last tab leaves.

Maybe if you tell me what you are trying to do I can suggest some other ideas.

**Comment by evolross** [comment]
Thanks for the response. I have some `setIntervals` that are querying external APIs, some `setIntervals` that are just updating/alternating a database/Collection object value that triggers display/configuration updates in my app (across all users). I want the intervals to keep running while the user is logged into the app.  And the nature of my app actually involves multiple open browser tabs (think multi-monitor-display stuff). So the user can navigate all throughout the app, on different templates and routes, but when they finally log out and/or disconnect (shut all tabs/windows) I need to `clearInterval` on the intervals they triggered as they don't need to keep firing and I want intervals running on the server forever.  It's only a few specific things to check for upon disconnection.

I realize now that the idea of using the user `Session` to `clearInterval` is probably really bad.  As the user could modify/drop/mess with their `Session` values and mess up the `clearInterval` call and it would run forever on the server.  So probably using a database flag is the best bet.

**Comment by evolross** [comment]
I was confused above... it looks like all `setIntervals` get cleared/killed when the user closes their browser/tab.  I was doing some testing with some really long `setIntervals` and I thought it appeared that the `setInterval` kept going even after the user closed their browser/tab.

If all the `setIntervals` get cleared automatically (since they were started on the client), I no longer need to do the type of checking I was talking about above.
