### ISSUE TITLE
Count all Users

### ISSUE THREAD

**Issue by victorperez** [mizzao/meteor-user-status#77]
I want to have a count of all users (including anonymous users) in the app, I have the below code:

```
//Server
Meteor.publish("sessions", function() {
  return UserStatus.connections.find({});
});
//Subscription
Router.route('/chat', {
 ...
  waitOn: function () {
    return Meteor.subscribe('sessions');
  },
 .....
});
//Client
Template.chat.helpers({
  usersOnline:function(){
    return UserStatus.connections.find({});
  },
  usersOnlineCount:function(){
   return UserStatus.connections.find({}).count();
  }
});
```

When I try to use 'usersOnlineCount' or 'usersOnline' in the template I get: Exception in template helper: TypeError: Cannot read property 'find' of undefined

What I'm doing wrong?

**Comment by mizzao** [comment]
`UserStatus.connections` is a non-database collection that exists only on the server. If you want to publish it to the client, follow the example in https://github.com/mizzao/meteor-user-status/blob/master/demo/.

However, you will probably quickly overload your server by doing this with any non-trivial number of users. It would be best to publish a count directly. `facts` publishes a session count which is done much more efficiently: https://github.com/meteor/meteor/blob/devel/packages/facts/

**Comment by victorperez** [comment]
Thanks to point me in the right direction, all I want to do is publish the actual anonymous user to the template and then check if this user is still online or not on another template, following the app demo I have the below code (I added a helper to return all the anonymous just to test if it is returning something):

if Meteor.isClient
  @UserConnections = new Mongo.Collection("user_status_sessions")

  Template.chat.helpers
    allAnonymous: -> UserConnections.find(userId: $exists: false)
    actualAnonymous: -> (?) //How I can get It?

  Template.singleConversation.helpers
    isOnline: (id) -> UserConnections.find(_id: id)

  Deps.autorun (c) ->
    try
      UserStatus.startMonitor
        threshold: 30000
        idleOnBlur: true
      c.stop()

if Meteor.isServer
  process.env.HTTP_FORWARDED_COUNT = 1

  Meteor.publish null, ->
    [
      Meteor.users.find { "status.online": true }, # online users only
        fields:
          status: 1,
          username: 1
      UserStatus.connections.find()
    ]

Whit this code 'allAnonymous' is always empty on the Template and is not returning nothing (no errors), could you help? Thanks.

**Comment by mizzao** [comment]
Can you please format the code properly when you post, using backticks? It is impossible to read.

**Comment by victorperez** [comment]
done, sry

**Comment by victorperez** [comment]
I resolved the error, thanks
