### ISSUE TITLE
Unable to retrieve Online Users data

### ISSUE THREAD

**Issue by nutanlade** [mizzao/meteor-user-status#78]
Hi,
I followed all steps mentioned but unable to retrieve online users data. Please correct me if anything missing. There are 2 users online. Attached are the screenshots of log printed and mongo db.

Server side :
server/onlineusers.js
Meteor.publish("userStatus", function() {
  return Meteor.users.find({ "status.online": true }, {fields: {'_id':1}});
});

Client side:
models/onlineusers.js
OnlineUsers = new Mongo.Collection("userStatus");

app.js
angular.module('abcapp').controller('OnlineUsersCtrl', ['$scope', '$meteor', function ($scope, $meteor) {
  $scope.onlineusers = $meteor.collection(OnlineUsers).subscribe('userStatus');
  console.log($scope.onlineusers);
}]);

Thanks,
Nutan
![screen shot 2015-08-31 at 8 43 51 am](https://cloud.githubusercontent.com/assets/5775600/9571524/7f4cebe6-4fbc-11e5-9ccb-e00d2f0127e0.png)
![screen shot 2015-08-31 at 8 44 58 am](https://cloud.githubusercontent.com/assets/5775600/9571530/9decbafe-4fbc-11e5-9451-46ab0be77b6b.png)

**Comment by mizzao** [comment]
You're not using Meteor correctly. The online states go into `Meteor.users` by default. See [this post I wrote](http://stackoverflow.com/a/18880927/586086) if you want to send it to a different collection (e.g. `OnlineUsers`).

By the way, what is that database query GUI app that you are using?

**Comment by nutanlade** [comment]
Hi Andrew,

I made below changes on client side to retrieve online users. The online
states are working as expected but following the example is not returning
the results.

$scope.$meteorSubscribe('users');
  var query = {};
  query['status.online'] = true;
  var online = $meteor.collection(function(){
    return Meteor.users.find(query, {fields: {'_id':1, 'profile.name':1,
'status.online':1}});
  });

Only after including 'status.online' in fields results are returned
properly. Also I'm new to Meteor.

Thanks for your response. If you could help me how could I implement the
same on server side would be helpful.

Thanks,
Nutan

On 2 September 2015 at 21:02, Andrew Mao <notifications@github.com> wrote:

> You're not using Meteor correctly. The online states go into Meteor.users
> by default. See this post I wrote
> <http://stackoverflow.com/a/18880927/586086> if you want to send it to a
> different collection (e.g. OnlineUsers).
>
> By the way, what is that database query GUI app that you are using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mizzao/meteor-user-status/issues/78#issuecomment-137134712>
> .
>



-- 
Thanks,
Nutan Kumar Lade

**Comment by mizzao** [comment]
You need to include the `status` field on the server query if you expect to find it on the client.

Sorry, but this is a question for StackOverflow, not a GitHub issue. You will find more help there.
