### ISSUE TITLE
angular meteor getting list of online users

### ISSUE THREAD

**Issue by kongaraju** [mizzao/meteor-user-status#79]
Am new to meteor development, could you please help me?

I am publishing 
// server
Meteor.publish("userData", function () {
  if (this.userId) {
    return Meteor.users.find({_id: this.userId});
  } else {
    this.ready();
  }
});

and on client side how can get the published users data?

**Comment by mizzao** [comment]
Sorry - this is a question for StackOverflow, not a GitHub issue. Please report bugs here only.
