### ISSUE TITLE
How can this behavior be explained?

### ISSUE THREAD

**Issue by dalgard** [mizzao/meteor-user-status#81]
I'm using a custom collection behavior (`sewdn:collection-behaviours`) which tracks the status field and I'm getting some weird results.

The **current** status field for one particular user looks like this:

```json
{
  "online": false,
  "lastLogin": {
    "date": ISODate("2015-08-28T12:34:38.194Z"),
    "ipAddr": "...",
    "userAgent": "..."
  }
}
```

And in my tracking array I have these entries:

```json
[
  {
    "status": {
      "online": false,
      "lastLogin": {
        "date": ISODate("2015-09-11T10:31:54.616Z"),
        "ipAddr": "...",
        "userAgent": "..."
      }
    },
    "trackedAt": ISODate("2015-09-11T12:50:49.972Z")
  },
  {
    "status": {
      "online": false,
      "lastLogin": {
        "date": ISODate("2015-08-19T06:44:11.263Z"),
        "ipAddr": "...",
        "userAgent": "..."
      }
    },
    "trackedAt": ISODate("2015-09-11T13:15:11.189Z")
  }
]
```

How come `online` is always `false`? And how come the latest tracked entry from today at `13:15:11` shows an **earlier** `lastLogin.date` than the previous one from today at `12:50:49`?

And how come the date in the **current** status field lies between the two tracked entries?

Thanks!

**Comment by mizzao** [comment]
You're going to have to provide more information about what `collection-behaviors` is doing.

`online` is `false` if the user is not connected. Also, I'm not sure how the tracking or `trackedAt` is generated, but if it's watching status field instead of the subfields, it's probably going to produce unexpected entries like these.

**Comment by dalgard** [comment]
That's a great start – I did feel sort of bad posting this not-so-specific issue.

The behavior I'm using is a custom version of "trackable" – [here](https://gist.github.com/dalgard/3566bfbbe01443306a6f). It works simply by copying the previous value of `status` and pushing it unto an array, every time the field is updated.

Could you elaborate on how tracking the whole `status` field will give weird results?

**Comment by dalgard** [comment]
> if it's watching status field instead of the subfields, it's probably going to produce unexpected entries like these.

Can you explain what you mean by this?

Seems to be the key to this unexpected behavior I am experiencing.

**Comment by mizzao** [comment]
I don't know, I was just speculating.

GitHub issues are not meant for technical support. However, if you find a bug in this package and you can replicate it, I'm happy to take a look.

**Comment by dalgard** [comment]
Fair enough. I was basically hoping that you would recognize the pattern directly, in relation to the way `mizzao:user-status` updates the field.

I'll look through the code of you package and track down the reason for the mentioned behavior – and then possibly return. Thanks for the package and sorry for the fuss.
