### ISSUE TITLE
User automatically goes Offline

### ISSUE THREAD

**Issue by guns2410** [mizzao/meteor-user-status#86]
I have been using this package for a while now. However, since the past few days, i am noticing that the user goes offline in about 10-15 seconds. i.e. status.online turns to false automatically.

Now this does not change even if user performs any activity on the app.

I guess, it was working perfect till 0.6.5, but now sure if there is something wrong.

P.S. I use it to observe the changes to the collection.

**Comment by shadowzick** [comment]
+1 for this

**Comment by legionzi** [comment]
Hi, @guns2410. Were you able to resolve it? I just had this issue last night. It was working perfectly fine and then all of a sudden it happened; the user goes offline immediately and sometimes it doesn't even go online.. Not sure but I did nothing that's related to the package that might cause this. Please help @guns2410 @mizzao @shadowzick. Thank you so much.
