### ISSUE TITLE
Help with user status

### ISSUE THREAD

**Issue by ickyrr** [mizzao/meteor-user-status#90]
Hi, I'm building an app right now, just a fairly simple application where users can see the users online. And this is a great package for that. I just hit on a problem though. I observed that when a user minimizes the app, or be 'idle' mode for a few minutes the status goes offline/idle, right? But the thing is, when the user maximizes or returns to the app, he's status still remains offline. 

Is this normal? or Should I do something about it?

Thanks, in advance, i'm pretty new to Meteor, so please go easy on me. :)

**Comment by mizzao** [comment]
Sorry, GitHub issues aren't for support requests. If you can identify a bug with the package, please post some code or an app that reproduces it and specify how to do so.
