### ISSUE TITLE
Error after adding meteor-users-status

### ISSUE THREAD

**Issue by gustavgans123** [mizzao/meteor-user-status#94]
Hello,

after adding meteor-user-status to my app, I get this error message by starting the app:

While building for web.browser:
error: no plugin found for bare_test_setup.coffee in coffeescript; a plugin for *.coffee was active when it was published but none is now
error: no plugin found for monitor.coffee in mizzao:user-status; a plugin for *.coffee was active when it was published but none is now.

I hope somebody can help me...thx!!

**Comment by mizzao** [comment]
This must be a Meteor 1.3 thing, I haven't had a chance to take a look yet...sorry.

**Comment by gustavgans123** [comment]
You are right..with Meteor 1.2.1 it's working!

**Comment by sri-p** [comment]
Even I am facing this issue with Meteor 1.3. Any updates on how to resolve this issue.

**Comment by likkhian** [comment]
Me too, on Meteor 1.3. I got this error after downloading the localmarket example and trying to run meteor.

**Comment by mizzao** [comment]
Can someone find out how the processing of .coffee files changed in Meteor 1.3?

**Comment by MereCommunication** [comment]
What worked for me on 1.3 is to remove the problem file (coffeescript) from C:\Users\merecommunication\AppData\Local\.meteor\packages and have it redownload. Something about the initial packages in 1.3 is off.

**Comment by likkhian** [comment]
Seconded. Deleting C:\Users\username\AppData\Local\.meteor\packages\coffeescript and running meteor in the app folder gets the app running.

**Comment by mizzao** [comment]
So it seems this might be a Meteor 1.3 glitch then, not necessarily an
issue with user-status?
