### ISSUE TITLE
Is this good for Meteor 1.3+

### ISSUE THREAD

**Issue by bmcgonag** [mizzao/meteor-user-status#97]
Just want to know if this is good to go for Meteor 1.3+ before I add it in.  

Maybe add-ins are version agnostic, but I figure better to ask.

**Comment by mizzao** [comment]
There have been some issues reported in #94.

**Comment by cheapRoc** [comment]
There's a good chance I'll be integrating this into our Meteor `1.3.2.4` oriented code base at some point in the near future. If we find anything borked we'll gladly contribute back any fixes or feedback.

**Comment by deadjdona** [comment]
What about Meteor 1.4.4?

**Comment by pgiani** [comment]
Just test it on 1.4.4 and it works

**Comment by mizzao** [comment]
FYI guys, you can always just run the [demo app](demo) on whatever version of Meteor you're wondering about; it tests most of the capabilities of the package.

**Comment by cheapRoc** [comment]
Sadly a year ago I never received the funding for continuing this upgrade. I've heard it does indeed work, as mizzaro mentioned. 😢

**Comment by bmcgonag** [comment]
FYI - I did add it to a meteor 1.5+ app, and it works.  Working quite well in fact, so thanks for the dev work on this.  Makes life much easir.  @cheapRoc Where can I donate to help support this work?
