### ISSUE TITLE
No status field after add this plugin

### ISSUE THREAD

**Issue by phuongtailtranminh** [mizzao/meteor-user-status#98]
Hi,

After I added this plugin by the following command:

> meteor add mizzao:user-status

And I tested, It seem doesn't work. And I checked the user object, there is no "status" field or "status.online" field.

My questions are:
- Do I need to manually add field to users collection after added this plugin?
- Do this plugin works on local (just development machine) or need upload to server?

**Comment by mizzao** [comment]
Unless this is a recent issue with Meteor 1.3, you're probably using it wrong. I encourage you to check out the demo app (in the repo) and test it out there.

**Comment by ay13** [comment]
I have this issue as well using Meteor 1.4.0.1. added the package and nothing seems to be updating in the user object. I tried `UserStatus.events.on("connectionLogin", function(fields) { console.log('fields', fields) })` on the server just to make sure it was installed and it worked just fine.
